<?php $productId=(int)($_GET['id']??0); require dirname(__DIR__) . '/_header.php'; ?>
<section class="section admin-form-page">
    <p class="eyebrow dark">INVENTARIS</p>
    <div class="page-title-row"><div><h1>Edit produk.</h1><p class="muted">Perbarui informasi produk tanpa merusak riwayat transaksi.</p></div><a class="button outline" href="../products.php">Kembali</a></div>
    <form id="productForm" class="product-form" enctype="multipart/form-data" data-product-id="<?= $productId ?>">
        <div class="form-section"><h2>Identitas produk</h2><div class="form-grid"><label>Nama produk <b>*</b><input class="input" name="name" required maxlength="180"></label><label>SKU / kode produk<input class="input" name="sku"></label><label>Kategori <b>*</b><select class="input" name="category_id" id="category_id" required></select></label><label>Satuan<input class="input" name="unit"></label></div><label>Deskripsi singkat<textarea class="input" name="short_description" maxlength="500"></textarea></label><label>Deskripsi lengkap<textarea class="input" name="description" rows="5"></textarea></label></div>
        <div class="form-section"><h2>Harga dan stok</h2><div class="form-grid"><label>Harga per hari <b>*</b><input class="input" type="number" name="price_per_day" min="0" required></label><label>Harga weekend<input class="input" type="number" name="weekend_price" min="0"></label><label>Deposit<input class="input" type="number" name="deposit" min="0"></label><label>Total stok <b>*</b><input class="input" type="number" name="stock" min="0" required></label><label>Minimal rental (hari)<input class="input" type="number" name="minimum_rental_days" min="1"></label><label>Maksimal rental (hari)<input class="input" type="number" name="maximum_rental_days" min="1"></label></div></div>
        <div class="form-section"><h2>Ketentuan rental</h2><div class="form-grid"><label>Denda keterlambatan<input class="input" type="number" name="late_fee" min="0"></label><label>Denda kerusakan<input class="input" type="number" name="damage_fee" min="0"></label><label>Denda kehilangan<input class="input" type="number" name="lost_fee" min="0"></label></div><label>Ketentuan penggunaan<textarea class="input" name="usage_terms" rows="3"></textarea></label><label>Ketentuan pengembalian<textarea class="input" name="return_terms" rows="3"></textarea></label><label>Ketentuan rental tambahan<textarea class="input" name="rental_terms" rows="3"></textarea></label></div>
        <div class="form-section"><h2>Foto produk</h2><div id="existingImages" class="image-preview"></div><label>Tambah foto gallery<input class="input" type="file" name="gallery" accept="image/jpeg,image/png,image/webp" multiple><small class="muted">JPG, PNG, atau WEBP. Maksimal 5 MB per file.</small></label><div id="imagePreview" class="image-preview"></div></div>
        <div class="form-section"><h2>Status</h2><label>Status produk<select class="input" name="status"><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select></label></div>
        <p id="productMessage" class="form-message"></p><button class="button" type="submit">Simpan perubahan</button>
    </form>
</section>
<script src="../../assets/js/admin.js"></script><script>loadProductForm();</script>
<?php require dirname(__DIR__) . '/_footer.php'; ?>
