<?php
require __DIR__ . '/bootstrap.php';
$user=requireLogin(); $pdo=db(); $input=body(); $method=$_SERVER['REQUEST_METHOD']; $id=(int)($_GET['id'] ?? 0);
if ($method==='GET') { $stmt=$pdo->prepare('SELECT c.*,p.name,p.image,p.price_per_day,p.stock FROM cart c JOIN products p ON p.id=c.product_id WHERE c.user_id=? ORDER BY c.created_at DESC'); $stmt->execute([$user['id']]); jsonResponse(true,'',$stmt->fetchAll()); }
requireCsrf($input);
if ($method==='POST') { $product=(int)($input['product_id']??0); $qty=max(1,(int)($input['quantity']??1)); $start=(string)($input['start_date']??''); $end=(string)($input['end_date']??''); if(!validDates($start,$end)||!checkAvailability($pdo,$product,$start,$end,$qty)) jsonResponse(false,'Tanggal atau stok tidak mencukupi.',null,422); $stmt=$pdo->prepare('INSERT INTO cart (user_id,product_id,quantity,start_date,end_date) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity),start_date=VALUES(start_date),end_date=VALUES(end_date)'); $stmt->execute([$user['id'],$product,$qty,$start,$end]); jsonResponse(true,'Produk ditambahkan ke keranjang.'); }
if ($method==='PUT' && $id) { $qty=max(1,(int)($input['quantity']??1)); $start=(string)($input['start_date']??''); $end=(string)($input['end_date']??''); $stmt=$pdo->prepare('SELECT product_id FROM cart WHERE id=? AND user_id=?'); $stmt->execute([$id,$user['id']]); $row=$stmt->fetch(); if(!$row||!validDates($start,$end)||!checkAvailability($pdo,(int)$row['product_id'],$start,$end,$qty)) jsonResponse(false,'Data cart atau stok tidak valid.',null,422); $stmt=$pdo->prepare('UPDATE cart SET quantity=?,start_date=?,end_date=? WHERE id=? AND user_id=?'); $stmt->execute([$qty,$start,$end,$id,$user['id']]); jsonResponse(true,'Keranjang diperbarui.'); }
if ($method==='DELETE' && $id) { $stmt=$pdo->prepare('DELETE FROM cart WHERE id=? AND user_id=?'); $stmt->execute([$id,$user['id']]); jsonResponse(true,'Produk dihapus.'); }
jsonResponse(false,'Permintaan cart tidak valid.',null,400);
